wikics:
  neighbor_masking_prob: 0.3
  embed_dropout_prob: 0.4
  dim_h: 1024
  dim_p: 256
  base_layer: 'Linear'
  activation: 'prelu'
  num_layer: 2
  use-ln: False
  learning_rate: 0.001
  weight_decay: 0
  train_epoch: 1500
  batch_size: 0


photo:
  neighbor_masking_prob: 0.4
  embed_dropout_prob: 0.4
  dim_h: 1024
  dim_p: 256
  base_layer: 'Linear'
  activation: 'prelu'
  num_layer: 2
  use-ln: True
  learning_rate: 0.001
  weight_decay: 0
  train_epoch: 1000
  batch_size: 0


computers:
  neighbor_masking_prob: 0.8
  embed_dropout_prob: 0.3
  dim_h: 1024
  dim_p: 256
  base_layer: 'Linear'
  activation: 'prelu'
  num_layer: 2
  use-ln: True
  learning_rate: 0.001
  weight_decay: 0
  train_epoch: 3000
  batch_size: 0


cs:
  neighbor_masking_prob: 0.95
  embed_dropout_prob: 0.7
  dim_h: 1024
  dim_p: 512
  base_layer: 'Linear'
  activation: 'prelu'
  num_layer: 2
  use-ln: True
  learning_rate: 0.0001
  weight_decay: 0
  train_epoch: 1500
  batch_size: 0


physics:
  neighbor_masking_prob: 0.8
  embed_dropout_prob: 0.55
  dim_h: 1024
  dim_p: 1024
  base_layer: 'Linear'
  activation: 'prelu'
  num_layer: 2
  use-ln: True
  learning_rate: 0.0005
  weight_decay: 0
  train_epoch: 500
  batch_size: 512


flickr:
  neighbor_masking_prob: 0.7
  embed_dropout_prob: 0.1
  dim_h: 1024
  dim_p: 512
  base_layer: 'GConv'
  activation: 'rrelu'
  num_layer: 2
  use-ln: True
  learning_rate: 0.0005
  weight_decay: 0
  train_epoch: 50
  batch_size: 0


ppi:
  neighbor_masking_prob: 0.5
  embed_dropout_prob: 0.4
  dim_h: 2048
  dim_p: 1024
  base_layer: 'GConv'
  activation: 'relu'
  num_layer: 2
  use-ln: True
  learning_rate: 0.001
  weight_decay: 0
  train_epoch: 1500
  batch_size: 0
